package com.androidstrike.schoolprojects.thefreighterapp.models

data class Dispatch(
    var status: String = "",
    var packageType: String = "",
    var weight: String = "",
    var amount: String = "",
    var client: String = "",
    var driver: String = "",
    var weigher: String = "",
    var statusChangeTime: String = "",
    var weighingDate: String = "",
    var lastUpdater: String = "",
    var pickupAddress: String = "",
    var pickupProvince: String = "",
    var pickupCountry: String = "",
    var pickupCountryCode: String = "",
    var pickupDate: String = "",
    var dropOffAddress: String = "",
    var dropOffProvince: String = "",
    var dropOffCountry: String = "",
    var dropOffCountryCode: String = "",
    var transitLocation: String = "",
    var userLocationRequest: Boolean = false,
    var pickerName: String = "",
    var pickerNumber: String = "",
    var interestedDrivers: Map<String, String> = mapOf(),
    var negotiationRound: String = "",
    var negotiationPrice0: String = "",
    var negotiationPrice1: String = "",
    var negotiationPrice2: String = "",
    var negotiationPrice3: String = "",
    var dateCreated: String = "",
    var dateWeighed: String = "",
    var datePickedUp: String = "",
    val dateDelivered: String = "",
    var dispatchId: String = "",
    var rating: String = "0"
)
